### ISSUE TITLE
Bot Permissions

### ISSUE THREAD

**Issue by AliOsm** [MasterGroosha/my-id-bot#10]
I'm using telegram.ext package to create bots, and I can't send messages to groups unless the admin gives my bot admin permissions, while your bot sends the messages after joining the group directly, do you have any guidance on that ?,?

**Comment by MasterGroosha** [comment]
This shouldn't be an issue at all. In groups which have less than 200 000 members, bots can send messages by default.

To help you with the issue, please provide more context on that. How can I reproduce this?

**Comment by AliOsm** [comment]
I think that I found the problem. The bot's group policy was enabled, I disabled it now and the bot should be able to send messages to groups directly, I'm testing this now.

**Comment by MasterGroosha** [comment]
You don't need privacy mode disabled for that

**Comment by AliOsm** [comment]
Actually, I tested it now and it worked fine after disabling the bot's groups policy. Before that the bot received "no permissions" errors when trying to send messages to groups without admin permissions.

**Comment by MasterGroosha** [comment]
That's strange, I've tried this code lots of times with different groups and supergroups and it worked fine.

Could you please show the exact error traceback?

**Comment by AliOsm** [comment]
This is the update output:

```bash
handlers.normal_user_handlers - WARNING - Update "None" caused error "Have no rights to send a message".
```

Caused by this code:

```python
context.bot.send_message(
    chat_id=chat_id, # This is the group ID where the bot is a member of it.
    text=text,
    parse_mode=PARSEMODE_MARKDOWN_V2,
    disable_web_page_preview=True,
)
```

The used package:

```
python-telegram-bot==13.7
```

**Comment by MasterGroosha** [comment]
Does this happen with any group or with particular one?
Also if you run my code, does the issus persist?

**Comment by AliOsm** [comment]
This happens with any group.

I didn't use your code yet, also the two packages are different,. I don't know if aiogram is implementing this in a different way other than python-telegram-bot.

**Comment by MasterGroosha** [comment]
Closed due to inactivity and because OP talks about some other code, not written by me
