### ISSUE TITLE
Feature: show ID of supergroups from forwarded messages

### ISSUE THREAD

**Issue by MasterGroosha** [MasterGroosha/my-id-bot#15]
Currently my bot can only tell [super]group ID if added to the group. However if a supergroup admin posted any message anonymously, the bot can tell supergroup's ID. 

Need to implement this.

**Comment by Qaz1235wsx** [comment]
> Currently my bot can only tell [super]group ID if added to the group. However if a supergroup admin posted any message anonymously, the bot can tell supergroup's ID.
> 
> Need to implement this.

**Comment by Qaz1235wsx** [comment]
> Currently my bot can only tell [super]group ID if added to the group. However if a supergroup admin posted any message anonymously, the bot can tell supergroup's ID. 
> 
> 
> 
> Need to implement this.

t.me/@id910143555

**Comment by MasterGroosha** [comment]
@Qaz1235wsx wtf

**Comment by MasterGroosha** [comment]
Done in 71b08f47c8d761e44fa9152883f6aeed94c8c330 with follow-up fix in a9fd03d1f05235c4add76290b7506c7e5020479b
